version: '3'    

services:
  alura-ts-1:
    image: node:15
    container_name: alura-ts-1
    env_file: .env
    restart: always
    working_dir: /home/node/app
    command: npm run server
    ports:
      - 8082:${API_PORT}
    volumes:
      - ./:/home/node/app